# Generated by Django 2.2.4 on 2019-10-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191022_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='produto-teste'),
            preserve_default=False,
        ),
    ]
